project:
  type: website
  output-dir: docs

website:
  title: "그냥 하는거지 뭐..."
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/leejuyeoun

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



